### ISSUE TITLE
Unable to use a dot in parameter names

### ISSUE THREAD

**Issue by pmzandbergen** [apidoc/apidoc-core#64]
I would like to use a dot in a parameter.

This is working:

`@apiParam   (Query) {String}    [filter]                    Filter on all fields`

Array notation is also working:

`@apiParam   (Query) {String}    [filter[username]]          Filter username`

Using a dot is **not** working:

`@apiParam   (Query) {String}    [filter[profile.name]]   Filter surname on profile`

I know the dot is reserved for grouping field names, however this should not be necessary at the array notation like in this example. It would be helpful to have an escape character (backslash) like:

`@apiParam   (Query) {String}    [filter[profile\.name]]   Filter surname on profile`

Is this possible? Example URL for this use-case:

`.../user?filter[profile.name]=John`

**Comment by tomislav13** [comment]
This is needed indeed

**Comment by rabindratamang** [comment]
This much needed but is it still not supported?

**Comment by sw360cab** [comment]
whether I use dot in the key of an obj definition it is completely ignored but no errors/warnings

Both 

* @apiSuccess (NotificationPayload) {String}  n.code   code of notification.

* @apiSuccess (NotificationPayload) {String}  n\.code   code of notification.

Results in:

code | String | code of notification.
-- | -- | --

instead of

n.code | String | code of notification.
-- | -- | --

Am I missing something?
